ElasticNet:
  alpha: [0.01, 0.1, 0.5, 1.0]
  l1_ratio: [0.1, 0.5, 0.7, 0.9]

RandomForest:
  n_estimators: [100, 200, 300]
  max_depth: [10, 20, 30, null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]

XGBoost:
  n_estimators: [100, 200, 300]
  max_depth: [3, 6, 10]
  learning_rate: [0.01, 0.1, 0.2]
  subsample: [0.8, 0.9, 1.0]

model_selection:
  cv_folds: 5
  scoring: 'neg_mean_squared_error'
  test_size: 0.2
  random_state: 42